# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  flutter_application_path = '../flutter_demo/'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

  # Pods for iOS_demo

  target 'iOS_demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS_demoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
